services:
  web:
    build: .
    container_name: drf_app
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:3002
      "
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - sqlite_data:/app/data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  sqlite_data: