# Generated by Django 6.0.6 on 2026-06-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IshonchEat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='IshonchEat.category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner_user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
