# Generated by Django 6.0.6 on 2026-06-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IshonchEat', '0002_restaurant_categories_alter_restaurant_owner_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_open',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
