# Generated by Django 6.0.6 on 2026-06-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IshonchEat', '0003_alter_advertisement_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
    ]
