# Generated by Django 6.0.6 on 2026-06-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IshonchEat', '0003_remove_menuitem_image_url_menuitem_img_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_img',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/'),
        ),
    ]
