# Generated by Django 6.0.6 on 2026-06-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IshonchEat', '0004_alter_menuitem_discount_alter_menuitem_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
