# Generated by Django 6.0.6 on 2026-06-24 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IshonchEat', '0005_menuitem_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='popular',
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_ads', models.ImageField(upload_to='ads/')),
                ('promotion', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='IshonchEat.restaurant')),
            ],
        ),
    ]
