# Generated by Django 6.0.6 on 2026-07-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IshonchEat', '0005_remove_menuitem_category_menuitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['owner_user_id']},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
