"""
Django settings for FoodDelivery project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    # set casting and default values
    DEBUG=(bool, False)
)



# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')



# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env('DEBUG')

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'IshonchEat',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Eng tepada turishi kerak
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <-- Add this right here!
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FoodDelivery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FoodDelivery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default' : env.db('DATABASE_URL')
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/






# CORS ruxsatnomasi (Hamma joydan ulanish uchun, ishlab chiqish jarayonida)
CORS_ALLOW_ALL_ORIGINS = True


# DRF sozlamalari: Autentifikatsiyani JWT orqali qilamiz
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # Add this
}

# Swagger UI configuration meta-data
SPECTACULAR_SETTINGS = {
    'TITLE': 'Ishonch Food Delivery API Swagger',
    'DESCRIPTION': 'Comprehensive API documentation for the IshonchFood backend system.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, # Setting this to False hides the schema endpoint itself

    #  Loads a theme that supports native light/dark switching hooks
    'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@5',

    # Make sure you aren't overriding component settings to be hidden
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True, # Keeps individual endpoints bookmarkable in the browser URL bar
        'displayOperationId': False, # Hides the internal technical Python function names from the UI
        'defaultModelsExpandDepth': 1, # Keeps data models neatly collapsed by default at the bottom of the page
        'defaultModelRendering': 'model',  # Shows the data model structure
        'displayRequestDuration': True, # Shows a timer tracking exactly how long an API request takes to return

       #'alpha' sorts your endpoints alphabetically within their tags
       #'method' sorts them by HTTP action (GET, POST, PUT, DELETE)
        'operationsSorter': 'alpha', 
       #'alpha' sorts the main sections (Tags) alphabetically
        'tagsSorter': 'alpha',

        'docExpansion': 'list',        # Endpoints load open and visible
       #'persistAuthorization': True,  # Remembers JWT tokens on refresh
       #'filter': True, # Quick search filter bar
    },

    # Use the default theme stylesheet so the dark mode utility scripts can read properties correctly
    'SWAGGER_UI_THEME': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css',
    
    # This automatically drops a script onto the page to let them switch manually!
    'SWAGGER_UI_THEME_EXTRA': [
        'https://cdn.jsdelivr.net/npm/swagger-ui-dark-mode-toggle@1.0.1/dist/swagger-ui-dark-mode-toggle.css',
    ],
    'SWAGGER_UI_JS': [
        'https://cdn.jsdelivr.net/npm/swagger-ui-dark-mode-toggle@1.0.1/dist/swagger-ui-dark-mode-toggle.js',
    ],
    

#     'TAGS': [
#     {
#         'name': 'Category',
#         'description': 'Category management endpoints. These APIs allow you to create, retrieve, and manage product categories within the system.',
#     },
#     {
#         'name': 'Restaurants',
#         'description': 'Operations involving restaurant registration, profile handling, and status updates.',
#     },
#     {
#         'name': 'Menu Items',
#         'description': 'Endpoints dedicated to managing catalog items, pricing structures, and discounts.',
#     },
# ],

    # This enables the Authorize button in Swagger for Bearer JWT Tokens
    'SECURITY': [{
        'BearerAuth': [],
    }],
    'COMPONENT_SPLIT_REQUEST': True,# Splits your data schemas into two separate variants: one for creating (POST/PUT) and one for reading (GET)
}


# IF DEBUG SWITCH (LOCAL VS PRODUCTION)
if DEBUG:
    STATIC_URL = 'static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
   
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

    
    # Only include the directory if it actually exists on the disk
    _global_static = os.path.join(BASE_DIR, 'static')
    if os.path.exists(_global_static):
        STATICFILES_DIRS = [_global_static]
    else:
        STATICFILES_DIRS = []

    # Use Django's default local file storage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

else:
    # --- PRODUCTION (WHITENOISE + AWS S3) ---
    # AWS S3 Settings
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = env('REGION_NAME')  # Change to your bucket's region


    # Prevents query string tokens from cluttering public URLs
    AWS_QUERYSTRING_AUTH = False 

    # Base URL domains for S3
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    
    # Subfolder organization inside the bucket
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

    STORAGES = {
        # Media files (Admin image uploads go here)
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "location": "media",
            },
        },
        
        # Static files (CSS, JS, Admin assets go here)
        "staticfiles": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "location": "static",
            },
        },
    }
