"""
Django settings for FoodDelivery project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    # set casting and default values
    DEBUG=(bool, False)
)

# Read the file definitions safely
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ✅ TO THIS (Bypasses django-environ parsing quirks completely):
SECRET_KEY = os.environ.get('SECRET_KEY')

# ✅ After (Force strip quotes to match FastAPI/Pydantic parsing behavior):
JWT_ACCESS_SECRET_KEY = str(os.environ.get('JWT_ACCESS_SECRET_KEY', '')).strip("'\" ")





# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env('DEBUG')

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'IshonchEat',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Eng tepada turishi kerak
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <-- Add this right here!
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'IshonchEat.authentication.JWTSharedSecretAuthentication',
]

ROOT_URLCONF = 'FoodDelivery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FoodDelivery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default' : env.db('DATABASE_URL')
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/






# CORS ruxsatnomasi (Hamma joydan ulanish uchun, ishlab chiqish jarayonida)
CORS_ALLOW_ALL_ORIGINS = True


# DRF sozlamalari: Autentifikatsiyani JWT orqali qilamiz
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # Add this
}

# Swagger UI configuration meta-data
SPECTACULAR_SETTINGS = {
    'TITLE': 'Ishonch Food Delivery API Swagger',
    'DESCRIPTION': 'Comprehensive API documentation for the IshonchFood backend system.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, 

    # Loads a theme that supports native light/dark switching hooks
    'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@5',

    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True, 
        'displayOperationId': False, 
        'defaultModelsExpandDepth': 1, 
        'defaultModelRendering': 'model',  
        'displayRequestDuration': True, 
        'operationsSorter': 'alpha', 
        'tagsSorter': 'alpha',
        'docExpansion': 'list',        
    },

    # Use the default theme stylesheet
    'SWAGGER_UI_THEME': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css',
    
    # Dark mode utility scripts
    'SWAGGER_UI_THEME_EXTRA': [
        'https://cdn.jsdelivr.net/npm/swagger-ui-dark-mode-toggle@1.0.1/dist/swagger-ui-dark-mode-toggle.css',
    ],
    'SWAGGER_UI_JS': [
        'https://cdn.jsdelivr.net/npm/swagger-ui-dark-mode-toggle@1.0.1/dist/swagger-ui-dark-mode-toggle.js',
    ],

    # 🌟 FIXED INDENTATION: These are now properly placed INSIDE the dictionary
    'SECURITY': [{'BearerAuth': []}],
    
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'Paste your raw Node.js access token below (Do NOT type "Bearer").'
            }
        }
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'AUTHENTICATION_WHITELIST': [],
    'CUSTOM_AUTHENTICATION_CLASSES':[],
}


# IF DEBUG SWITCH (LOCAL VS PRODUCTION)
if DEBUG:
    STATIC_URL = 'static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
   
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

    
    # Only include the directory if it actually exists on the disk
    _global_static = os.path.join(BASE_DIR, 'static')
    if os.path.exists(_global_static):
        STATICFILES_DIRS = [_global_static]
    else:
        STATICFILES_DIRS = []

    # Use Django's default local file storage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

else:
    # --- PRODUCTION (WHITENOISE + AWS S3) ---
    # AWS S3 Settings
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = env('REGION_NAME')  # Change to your bucket's region


    # Prevents query string tokens from cluttering public URLs
    AWS_QUERYSTRING_AUTH = False 

    # Base URL domains for S3
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    
    # Subfolder organization inside the bucket
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

    STORAGES = {
        # Media files (Admin image uploads go here)
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "location": "media",
            },
        },
        
        # Static files (CSS, JS, Admin assets go here)
        "staticfiles": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "location": "static",
            },
        },
    }
